import type { Language } from './types'

/**
 * Konkani is written first. English is the second language, not the “master” UI.
 * Keep sentences short so Listen / Sathi Says stay easy to hear.
 */
const kn = {
  appName: 'मत्स्य साथी',
  meaning: 'मासळ्याचो साथी',
  place: 'गोय',
  continue: 'पुढे चला',
  skip: 'सोडा',
  back: 'फाटीं',
  done: 'झालें',
  next: 'पुढें',
  listen: 'ऐका',
  showMe: 'दाखवा',
  speak: 'बोला',
  askByVoice: 'बोलून विचारा',
  comingLater: 'हें फुडच्या टप्प्यांत येतलें.',
  tapInstead: 'आवाज ना. बटण दाबा.',
  languageTitle: 'भास वेंचात',
  konkani: 'कोंकणी',
  english: 'English',
  sathiLanguage: 'पयलीं भास वेंचात.',
  roleTitle: 'हें फोन कोणाखातीर?',
  fisher: 'मासळीकार',
  family: 'कुटुंब',
  sathiRole: 'हें फोन कोण वापरता?',
  simpleTitle: 'सोपें रूप',
  simpleBody: 'मोठीं बटणां. कमी वाचप. चड आवाज.',
  useSimple: 'सोपें रूप वापरात',
  notNow: 'आतां न्हय',
  voiceOn: 'आवाज चालू',
  voiceOff: 'आवाज बंद',
  sathiSimple: 'मोठीं बटणां. तुमी ऐकूंक आनी बोलूंक शकतात.',
  profileTitle: 'तुमचें नांव',
  useDemo: 'डेमो प्रोफाइल वापरात',
  sathiProfile: 'नांव दवरात, उपरांत घरा.',
  howTitle: 'मत्स्य साथी कसो काम करता',
  goHome: 'घरा वचात',
  boat: 'बोट',
  beacon: 'साथि बीकन',
  network: 'नेटवर्क',
  familyNode: 'कुटुंब',
  sathiHow: 'कुटुंब तुमकां साथि बीकनातल्यान पळयता.',
  homeLabel: 'घर',
  schemesNav: 'योजना',
  seaNav: 'समुद्र',
  tripNav: 'प्रवास',
  startTrip: 'प्रवास सुरू करा',
  sos: 'SOS',
  sosHint: 'मदत',
  sathiSays: '🔊 साथि सांगता',
  sathiHome: 'आज समुद्राची परिस्थिती सुरक्षित आहे.',
  qSea: 'आज समुद्र कसो?',
  qSchemes: 'सरकारी मदत',
  qFamily: 'माझें कुटुंब',
  qHelp: 'मदत जाय?',
  seaSafe: 'सुरक्षित',
  seaCaution: 'सावधान',
  seaEmergency: 'आपत्काल',
  schemesStatus: '२ योजना',
  familyReady: 'तयार',
  helpIdle: 'SOS',
  statusSafe: 'SAFE',
  statusCaution: 'CAUTION',
  statusEmergency: 'EMERGENCY',
  familySoon: 'कुटुंबाचें पान फुडें येतलें.',
  showSea: 'आज समुद्र सुरक्षित आसा.',
  showSchemes: 'सरकारी मदत इहां दाखयता.',
  showFamily: 'कुटुंब तुमकां पळोवंक तयार आसा.',
  showHelp: 'खरे संकटांत SOS दाबा. आवाजान SOS वचोना.',
  listenSea: 'आज समुद्र सुरक्षित आसा. वचूंक जाता.',
  listenSchemes: 'तुमचे खातीर दोन सरकारी योजना आसात.',
  listenFamily: 'तुमी भायर गेल्यार कुटुंब पळयतले.',
  listenHelp: 'मदत जाय जाल्यार तळाचें लाल बटण दाबा. बोलून SOS वचोना.',
  listenHome: 'आज समुद्र सुरक्षित आसा. कुटुंब तयार आसा.',
  noticeTrip: 'प्रवास फुडच्या टप्प्यांत सुरू जातलो.',
  noticeSos: 'SOS फुडच्या टप्प्यांत. आवाजान SOS वचोना.',
  noticeTab: 'हें पान फुडच्या टप्प्यांत.',
  speaking: 'आयकता…',
}

const en = {
  appName: 'Matsya Sathi',
  meaning: "Fisherman's companion",
  place: 'Goa',
  continue: 'Continue',
  skip: 'Skip',
  back: 'Back',
  done: 'Done',
  next: 'Next',
  listen: 'Listen',
  showMe: 'Show me',
  speak: 'Speak',
  askByVoice: 'Ask by speaking',
  comingLater: 'This continues in a later step.',
  tapInstead: 'Voice not available. Please tap.',
  languageTitle: 'Choose language',
  konkani: 'कोंकणी',
  english: 'English',
  sathiLanguage: 'First, choose a language.',
  roleTitle: 'Who is this phone for?',
  fisher: 'Fisherman',
  family: 'Family',
  sathiRole: 'Who is using this phone?',
  simpleTitle: 'Simple Mode',
  simpleBody: 'Bigger buttons. Less reading. More voice.',
  useSimple: 'Use Simple Mode',
  notNow: 'Not now',
  voiceOn: 'Voice on',
  voiceOff: 'Voice off',
  sathiSimple: 'Bigger buttons. You can listen and speak.',
  profileTitle: 'Your name',
  useDemo: 'Use demo profile',
  sathiProfile: 'Then we go home.',
  howTitle: 'How Matsya Sathi works',
  goHome: 'Go to Home',
  boat: 'Boat',
  beacon: 'Sathi Beacon',
  network: 'Network',
  familyNode: 'Family',
  sathiHow: 'Your family can see you through Sathi Beacon.',
  homeLabel: 'Home',
  schemesNav: 'Schemes',
  seaNav: 'Sea',
  tripNav: 'Trip',
  startTrip: 'Start trip',
  sos: 'SOS',
  sosHint: 'Help',
  sathiSays: '🔊 Sathi says',
  sathiHome: 'Today the sea is safe.',
  qSea: 'Can I go to sea today?',
  qSchemes: 'Government help',
  qFamily: 'Can my family see me?',
  qHelp: 'Do I need help?',
  seaSafe: 'SAFE',
  seaCaution: 'CAUTION',
  seaEmergency: 'EMERGENCY',
  schemesStatus: '2 schemes',
  familyReady: 'READY',
  helpIdle: 'SOS',
  statusSafe: 'SAFE',
  statusCaution: 'CAUTION',
  statusEmergency: 'EMERGENCY',
  familySoon: 'The family screen comes in a later step.',
  showSea: 'Today the sea is safe.',
  showSchemes: 'Government help is here.',
  showFamily: 'Your family is ready to see you.',
  showHelp: 'In real danger, tap SOS. Speech never sends SOS.',
  listenSea: 'Today the sea is safe. You may go.',
  listenSchemes: 'Two government schemes may apply to you.',
  listenFamily: 'When you go out, your family can see you.',
  listenHelp: 'If you need help, tap the red SOS button. Speaking will not send SOS.',
  listenHome: 'Today the sea is safe. Your family is ready.',
  noticeTrip: 'Starting a trip comes in a later step.',
  noticeSos: 'SOS comes in a later step. Speech never sends SOS.',
  noticeTab: 'This screen comes in a later step.',
  speaking: 'Listening…',
}

export type Copy = typeof kn

export function getCopy(language: Language): Copy {
  return language === 'en' ? en : kn
}

export const demoProfileKn = {
  displayName: 'राम',
  boatName: 'सागर',
  village: 'कॅलंगुट',
}

export const demoProfileEn = {
  displayName: 'Ram',
  boatName: 'Sagar',
  village: 'Calangute',
}
